<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChatApp.Domain\ChatApp.Domain.csproj"/>
    <ProjectReference Include="..\ChatApp.DAL\ChatApp.DAL.csproj"/>
  </ItemGroup>
</Project>
