# name: CI — Build & Test

# on:
#   push:
#     branches: [dev]
#   pull_request:
#     branches: [dev]

# jobs:
#   build-and-test:
#     name: Build & Test (.NET 8)
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:16
#         env:
#           POSTGRES_DB: nexchat_test
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     env:
#       ConnectionStrings__Postgres: "Host=localhost;Port=5432;Database=nexchat_test;Username=postgres;Password=postgres"
#       ASPNETCORE_ENVIRONMENT: Development

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup .NET 8
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: 8.x

#       - name: Restore dependencies
#         run: dotnet restore NexChat.sln

#       - name: Build (Release)
#         run: dotnet build NexChat.sln --configuration Release --no-restore

#       - name: Run tests
#         run: dotnet test NexChat.sln --configuration Release --no-build --verbosity normal


name: Chat API CI

on:
  push:
    branches: [dev]

  pull_request:
    branches: [dev]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore NexChat.sln

      - name: Build
        run: dotnet build NexChat.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test NexChat.sln --configuration Release --no-build

      - name : Publish Application
        run: dotnet publish NexChat.sln --configuration Realease --output ./publsih

      - name: Show Publish Output
        run: ls -R ./publish
