name: Chat API CI

on:
  push:
    branches: [dev]

  pull_request:
    branches: [dev]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore NexChat.sln

      - name: Build
        run: dotnet build NexChat.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test NexChat.sln --configuration Release --no-build

      - name : Publish Application
        run: dotnet publish NexChat.sln --configuration Release --output ./publish

      - name: Show Publish Output
        run: ls -R ./publish

      - name: Uplaod Publish Output
        uses: actions/upload-artifact@v4
        with: 
           name: publish-files
           path: ./publish

  deploy: 
        
       needs: build-and-test

       runs-on: ubuntu-latest

       steps:
         - name: Download Artifact
           uses: actions/download-artifact@v4
           with:
            name: publish-files

         - name: Show Download Files
           run: ls- R

         





